---
# tasks file for ansible-role-gitlab-ce
- name: "Add gitlab-ce apt key"
  apt_key:
    url: "https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey"
    id: "14219A96E15E78F4"
- name: "Add apt repository of gitlab-ce"
  apt_repository:
    repo: "deb https://packages.gitlab.com/gitlab/gitlab-ce/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} main"
- name: "Install gitlab-ce"
  apt:
    name: gitlab-ce
  notify: reconfigure gitlab
- name: "Update gitlab.rb"
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
    validate: '/opt/gitlab/embedded/bin/ruby -c %s'
  notify: reconfigure gitlab

- name: "Install gitlab-backup timer"
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify: enable a timer for gitlab-backup
  with_items:
  - "gitlab-backup.service"
  - "gitlab-backup.timer"

- name: "Install gitlab-misc-backup timer"
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify: enable a timer for gitlab-misc-backup
  with_items:
  - "gitlab-misc-backup.service"
  - "gitlab-misc-backup.timer"
- name: "Install gitlab-misc-backup script"
  copy:
    src: "gitlab-misc-backup.sh"
    dest: "/etc/gitlab/gitlab-misc-backup.sh"
    owner: root
    group: root
    mode: 0755
  notify: enable a timer for gitlab-misc-backup

- name: "Install gitlab-remove-old-backup timer"
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify: enable a timer for gitlab-remove-old-backup
  with_items:
  - "gitlab-remove-old-backup.service"
  - "gitlab-remove-old-backup.timer"
- name: "Install gitlab-remove-old-backup script"
  template:
    src: "gitlab-remove-old-backup.sh.j2"
    dest: "/etc/gitlab/gitlab-remove-old-backup.sh"
    owner: root
    group: root
    mode: 0755
  notify: enable a timer for gitlab-remove-old-backup
