---
# handlers file for ansible-role-gitlab-ce
- name: reconfigure gitlab
  command: gitlab-ctl reconfigure
- name: enable a timer for gitlab-backup
  systemd:
    name: gitlab-backup.timer
    state: started
    enabled: yes
    daemon_reload: yes
- name: enable a timer for gitlab-mattermost-backup
  systemd:
    name: gitlab-mattermost-backup.timer
    state: started
    enabled: yes
    daemon_reload: yes
